### ISSUE TITLE
Cannot access http://biit.cs.ut.ee/clustvis/

### ISSUE THREAD

**Issue by Jannto** [taunometsalu/ClustVis#5] opened 2017-07-05 10:43 UTC
Hi, I cannot access the ClustVis website and was wondering if it is down for maintenance? In this case, wuld it be possible to get an estimate when the site is up again? All best wishes, Jannto

![clustvis](https://user-images.githubusercontent.com/29917812/27861081-94c312e4-617f-11e7-8fff-16001a20aec2.JPG)
, Zaragoza, Spain

**Comment by taunometsalu** [comment] 2017-07-05 11:03
Hi, there is a known issue related with a limitation of the open source Shiny server. All users share a single process and longer-running calculations can make the tool inaccessible to other users for a while. 

We are trying to solve it by using a load balancer, but at the moment, I can suggest to try again later (at the moment, it is running again) or use [another ClustVis edition](http://biit.cs.ut.ee/clustvis_large/).

**Comment by taunometsalu** [comment] 2017-12-11 14:10
Duplicate of https://github.com/taunometsalu/ClustVis/issues/7

**Closed as completed by taunometsalu** 2017-12-11 14:10 UTC

**Comment by noor-albader** [comment] 2018-08-06 22:07
Hey so both editions I have found, including the ClustVis edition link above, are "greyed" out and there is not any option or tabs to upload data. Does this mean the webtool/website is down or running another jobs and can't take anymore jobs?
thanks!

**Comment by taunometsalu** [comment] 2018-08-07 11:19
Sorry about that, we had a mistake in the configuration, should be fine again now.
